# S:\SDE\Hard Core\Learn\Golang\Projects\URL-Shortner-with-Go\Backend\docker-compose.yml
services:
  url-shortener:
    build: .
    ports:
      - "8080:8080"
    environment:
      - STORE_TYPE=postgres  # You can change this to redis or memory
      - POSTGRES_DSN=host=postgres user=postgres dbname=url_shortener password=1234 port=5432 sslmode=disable
      - REDIS_ADDR=redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=url_shortener
    networks:
      - app-network

  redis:
    image: redis:latest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
