version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  url-shortener:
    build: .
    environment:
      POSTGRES_DSN: "host=postgres user=postgres password=1234 dbname=postgres port=5432 sslmode=disable"
      REDIS_ADDR: "redis:6379"
      SERVER_PORT: "8080"
    ports:
      - "8080:8080"

volumes:
  postgres-data:
