apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: yourdockerhubusername/url-shortener:latest  # Push your Docker image to Docker Hub
        ports:
        - containerPort: 8080
        env:
        - name: STORE_TYPE
          value: "postgres"  # Or "redis", "memory"
        - name: POSTGRES_DSN
          value: "host=postgres user=postgres dbname=url_shortener password=1234 port=5432 sslmode=disable"
        - name: REDIS_ADDR
          value: "redis:6379"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener
spec:
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
