apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: <your-docker-image>:latest
        ports:
        - containerPort: 8080
        env:
          - name: POSTGRES_DSN
            valueFrom:
              secretKeyRef:
                name: postgres-dsn
                key: POSTGRES_DSN
          - name: REDIS_ADDR
            valueFrom:
              secretKeyRef:
                name: redis-addr
                key: REDIS_ADDR
